import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {Button, Input, Spacer, TextLink} from '../components';
import ButtonBack from '../components/atoms/Button/ButtonBack';
import styles from '../styles/ForgotPassword.module.css'

const Signup: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Client Eye</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={styles.sectionLeft}>
          <div className={styles.wrapper}>
            <ButtonBack/>
            <Spacer height={184} />
            <h1>Forgot Password?</h1>
            <Spacer height={31}/>
            <p>Enter the email that you used when you joined & we’ll send you a verification code to your email</p>
            <Spacer height={31}/>
            <Input type='email' placeholder='eg: johndoe@gmail.com' icon="icon-mail.svg" suffixIcon='icon-check-circle.svg'/>
            <Spacer height={25}/>
            <Button href='/resetPassword' title="Send Verification Code" backgroundColor/>
            <TextLink href="/signup" subTitle="Don’t have an account yet?" title=" Sign up now"/>
          </div>
        </section>
        <section className={styles.sectionRight}>
          <Image src="/images/img-background.png" alt='background' width={855} height={1014} layout='responsive' objectFit='contain' className={styles.backgroundImage} />
          <div>
            <Image src="/images/logo-white.svg" alt="logo client eye" width={120} height={120} />
            <p>ClientEye</p>
          </div>
        </section>
      </main>
    </div>
  )
}

export default Signup
