import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import {Button, Input, Spacer, TextLink} from '../components';
import ButtonBack from '../components/atoms/Button/ButtonBack';
import styles from '../styles/ResetPassword.module.css'

const Signup: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Client Eye</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={styles.sectionLeft}>
          <div className={styles.wrapper}>
            <ButtonBack/>
            <Spacer height={84} />
            <h1>Reset Password</h1>
            <Spacer height={31}/>
            <p>Please enter the verification code that you have recieved to your registered email address</p>
            <Spacer height={31}/>
            <Input type='text' placeholder='Enter your verification code' icon="icon-shield.svg" suffixIcon='verification'/>
            <div className={styles.resendCode}>
              <Link href="">
                <a>Resend Code</a>
              </Link>
            </div>
            <Input type='password' placeholder='Enter your new password' icon="icon-lock.svg" suffixIcon='icon-check-circle.svg'/>
            <Spacer height={19}/>
            <Input type='password' placeholder='Confirm password' icon="icon-lock.svg" suffixIcon='icon-check-circle.svg'/>
            <Spacer height={25}/>
            <Button href='/' title="Reset your password" backgroundColor/>
            <TextLink href="/signup" subTitle="Don’t have an account yet?" title=" Sign up now"/>
          </div>
        </section>
        <section className={styles.sectionRight}>
          <Image src="/images/img-background.png" alt='background' width={855} height={1014} layout='responsive' objectFit='contain' className={styles.backgroundImage} />
          <div>
            <Image src="/images/logo-white.svg" alt="logo client eye" width={120} height={120} />
            <p>ClientEye</p>
          </div>
        </section>
      </main>
    </div>
  )
}

export default Signup
