import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import {Button, Input, Spacer, TextLink} from '../components';
import styles from '../styles/Signup.module.css'

const Signup: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Client Eye</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={styles.sectionLeft}>
          <div className={styles.wrapper}>
            <h1>Create an account</h1>
            <div className={styles.btnSocial}>
              <Button href='/' title="Google" icon="/icons/google.svg" />
              <Spacer width={26}/>
              <Button href='/' title="Apple ID" icon="/icons/apple.svg" />
            </div>
            <div className={styles.line}>
              <div/>
                <p>Or </p>
              <div/>
            </div>
              <div className={styles.wrapperNameInput}>
                <Input type='text' placeholder='Firstname' icon="icon-user.svg"/>
                <Input type='text' placeholder='Lastname' icon="icon-user.svg" />  
              </div>
              <Spacer height={25}/>
              <Input type='email' placeholder='eg: johndoe@gmail.com' icon="icon-mail.svg"/>
              <Spacer height={25}/>
              <Input type='password' placeholder='Enter your password' icon="icon-lock.svg" suffixIcon='icon-eye.svg'/>
            <div className={styles.term}>
              <input type="checkbox" />
              <p>I agree to the <Link href="/termAndCondition"><a>Terms and Conditions</a></Link></p>
            </div>
            <Button href='/' title="Sign up to your account" backgroundColor/>
            <TextLink href="/login" subTitle="Already have an account?" title="Sign in"/>
          </div>
        </section>
        <section className={styles.sectionRight}>
          <Image src="/images/img-background.png" alt='background' width={855} height={1014} layout='responsive' objectFit='contain' className={styles.backgroundImage} />
          <div>
            <Image src="/images/logo-white.svg" alt="logo client eye" width={120} height={120} />
            <p>ClientEye</p>
          </div>
        </section>
      </main>
    </div>
  )
}

export default Signup
